INSERT INTO modules (course) VALUES ('Docker');
INSERT INTO modules (course) VALUES ('Padrões e técnicas avançadas com o Git e Github');
INSERT INTO modules (course) VALUES ('Integração contínua');
INSERT INTO modules (course) VALUES ('Kubernetes');
INSERT INTO modules (course) VALUES ('Fundamentos de Arquitetura de Software'); 
INSERT INTO modules (course) VALUES ('Comunicação'); 
INSERT INTO modules (course) VALUES ('RabbitMQ'); 
INSERT INTO modules (course) VALUES ('Microsserviõs - API do Catálogo com Node.js'); 
INSERT INTO modules (course) VALUES ('Domain Driven Design e Arquitetura hexagonal'); 
INSERT INTO modules (course) VALUES ('Arquitetura do projeto prático - Codeflix'); 
INSERT INTO modules (course) VALUES ('Microsserviço: Catálogo de vídeos com Laravel ( Back-end )');